### ISSUE TITLE
到了 最后一步 node server.js运行时候 老是报错  求大神解救 564297479

### ISSUE THREAD

**Issue by Xuhengfeng** [tangdaohai/vue-ssr-demo#2]
app.use(async (ctx, next) => {
              ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by Aron0429** [comment]
同问

**Comment by tangdaohai** [comment]
请先升级 node 到最新稳定版本。

**Comment by Xuhengfeng** [comment]
谢谢,    已经过去好几个月了， 我现在开始采用nuxt去写了
